Repository meilisearch/meilisearch-python, pull requests merged in 2022-09, with the labels that each got.

#519 Add pipenv install in the CONTRIBUTING guide
  CONTRIBUTING.md
Labels: documentation

#520 Fix update document test after update to v0.29
  tests/index/test_index_document_meilisearch.py
Labels: bug

#521 Add a creation key use case with wildcards in the action field
  tests/client/test_client_key_meilisearch.py
Labels: enhancement

#533 Update version for the next release (v0.20.0)
  meilisearch/version.py
Labels: skip-changelog

#529 Drop python 3.6 support
  .github/workflows/pre-release-tests.yml
  .github/workflows/tests.yml
  README.md
  bors.toml
  meilisearch/_httprequests.py
  meilisearch/client.py
  meilisearch/config.py
  meilisearch/errors.py
  meilisearch/index.py
  meilisearch/models/document.py
  meilisearch/models/index.py
  meilisearch/models/task.py
  meilisearch/task.py
  meilisearch/version.py
  setup.py
  tests/client/test_client_version_meilisearch.py
  tests/client/test_http_requests.py
  tests/conftest.py
  tests/settings/test_settings.py
  tests/settings/test_settings_distinct_attribute_meilisearch.py
  tests/settings/test_settings_ranking_rules_meilisearch.py
  tests/settings/test_settings_stop_words_meilisearch.py
  tests/settings/test_settings_synonyms_meilisearch.py
  tox.ini
Labels: breaking-change

#535 Fix require package
  setup.py
Labels: bug

#537 Update version for the next release (v0.21.0)
  meilisearch/version.py
Labels: skip-changelog
