Repository meilisearch/meilisearch-python, pull requests merged in 2023-10, with the labels that each got.

#864 Fix facet_search parameter order in documentation
  .code-samples.meilisearch.yaml
Labels: skip-changelog

#861 Add dependency cache in CI
  .github/workflows/pre-release-tests.yml
  .github/workflows/pypi-publish.yml
  .github/workflows/tests.yml
Labels: skip-changelog

#859 Add testing for Python 3.12
  .github/workflows/tests.yml
  bors.toml
  pyproject.toml
Labels: maintenance

#868 fix: replace the code sample related to the `delete_documents` method…
  .code-samples.meilisearch.yaml
Labels: skip-changelog

#871 Support text separator customization
  .code-samples.meilisearch.yaml
  meilisearch/config.py
  meilisearch/index.py
  tests/settings/test_settings_text_separators_meilisearch.py
Labels: enhancement

#873 Update version for the next release (v0.28.4)
  meilisearch/version.py
Labels: skip-changelog

#875 Automation version update
  .github/workflows/update-version.yml
  CONTRIBUTING.md
Labels: maintenance
