Repository meilisearch/meilisearch-python, pull requests merged in 2023-02, with the labels that each got.

#674 Fix pylint and isort errors
  Pipfile
  Pipfile.lock
  meilisearch/client.py
Labels: dependencies, skip-changelog

#673 Fix parameter name in docstring
  meilisearch/client.py
Labels: skip-changelog

#675 test_delete_all_tasks updated
  tests/client/test_client_task_meilisearch.py
Labels: skip-changelog

#676 Update the return type of methods
  meilisearch/client.py
  meilisearch/index.py
  meilisearch/models/index.py
  meilisearch/models/key.py
  tests/client/test_client_dumps.py
  tests/client/test_client_key_meilisearch.py
  tests/client/test_client_task_meilisearch.py
  tests/client/test_client_tenant_token.py
  tests/conftest.py
  tests/index/test_index.py
  tests/index/test_index_search_meilisearch.py
  tests/index/test_index_task_meilisearch.py
  tests/settings/test_setting_faceting.py
  tests/settings/test_settings.py
  tests/settings/test_settings_displayed_attributes_meilisearch.py
  tests/settings/test_settings_distinct_attribute_meilisearch.py
  tests/settings/test_settings_filterable_attributes_meilisearch.py
  tests/settings/test_settings_pagination.py
  tests/settings/test_settings_ranking_rules_meilisearch.py
  tests/settings/test_settings_searchable_attributes_meilisearch.py
  tests/settings/test_settings_sortable_attributes_meilisearch.py
  tests/settings/test_settings_stop_words_meilisearch.py
  tests/settings/test_settings_synonyms_meilisearch.py
  tests/settings/test_settings_typo_tolerance_meilisearch.py
Labels: breaking-change

#693 Update version for the next release (v0.25.0)
  meilisearch/version.py
Labels: skip-changelog
