Repository meilisearch/meilisearch-python, pull requests merged in 2024-02, with the labels that each got.

#924 Implement vector search experimental feature v2 (v1.6)
  README.md
  meilisearch/config.py
  meilisearch/index.py
  meilisearch/models/index.py
  tests/conftest.py
  tests/index/test_index_search_meilisearch.py
  tests/settings/test_settings_embedders.py
Labels: enhancement, breaking-change

#927 Make embedders deseralize to correct type
  meilisearch/index.py
  tests/conftest.py
  tests/settings/test_settings.py
  tests/settings/test_settings_embedders.py
Labels: bug

#929 Add dimensions to OpenAI model
  meilisearch/models/index.py
Labels: enhancement

#931 Update author
  pyproject.toml
Labels: maintenance
