Repository meilisearch/meilisearch-python, pull requests merged in 2024-06, with the labels that each got.

#971 Add proximityPrecision setting
  .code-samples.meilisearch.yaml
  meilisearch/_httprequests.py
  meilisearch/config.py
  meilisearch/index.py
  meilisearch/models/index.py
  tests/settings/test_settings_proximity_precision_meilisearch.py
Labels: enhancement

#974 Allow passing a custom serializer for documents
  README.md
  meilisearch/_httprequests.py
  meilisearch/index.py
  tests/index/test_index_document_meilisearch.py
Labels: enhancement

#977 Remove extra line from readme example
  README.md
Labels: skip-changelog

#978 Fix flaky test
  tests/settings/test_settings.py
Labels: maintenance
