Repository meilisearch/meilisearch-python, pull requests merged in 2025-06, with the labels that each got.

#1068 Add methods for new index settings: `facetSearch` and `prefixSearch`
  .code-samples.meilisearch.yaml
  meilisearch/_httprequests.py
  meilisearch/config.py
  meilisearch/index.py
  meilisearch/models/index.py
  tests/settings/test_settings_facet_search.py
  tests/settings/test_settings_prefix_search.py
Labels: enhancement

#1117 Add merge_group to trigger tests
  .github/workflows/tests.yml
Labels: maintenance

#1113 Fix Document model: bad test, attribute bug, and field cleanup
  meilisearch/models/document.py
  tests/models/test_document.py
Labels: enhancement, breaking-change

#1116 Add `disableOnNumbers` to typo tolerance settings
  .code-samples.meilisearch.yaml
  meilisearch/models/index.py
  tests/settings/test_settings_typo_tolerance_meilisearch.py
Labels: enhancement

#1066 Refactor task model and params
  meilisearch/index.py
  meilisearch/models/index.py
  meilisearch/models/task.py
  meilisearch/task.py
  tests/models/test_index.py
Labels: breaking-change
